MVC-fab/MVC_Version/MVC_Version/Controllers/CollegeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Version.Controllers
{
    public class CollegeController : Controller
    {
        // GET: College
        public ActionResult Colofcd()
        {
            return View();
        }

        public ActionResult Colofed()
        {
            return View();
        }

        public ActionResult Coloflaw()
        {
            return View();
        }

        public ActionResult Schofmus()
        {
            return View();
        }

    }
}

MVC-fab/MVC_Version/MVC_Version/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Version.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC-fab/MVC_Version/MVC_Version/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<section id="main">
    <div class="container">
        <article id="main-col">
            <h1 class="page-title">About Us</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed malesuada, erat id lobortis congue, lacus velit tempus leo, blandit tempus urna augue ac ante. Duis vehicula tortor dui, ut faucibus neque placerat vel. Vivamus tempor ullamcorper velit et pretium. Quisque hendrerit ac est quis facilisis. Integer volutpat massa at sem suscipit maximus. Phasellus rutrum ac ex vel porttitor. Fusce at hendrerit velit. Morbi et sapien ut odio tristique egestas nec vitae nunc. Pellentesque vitae libero non turpis mattis accumsan.</p>
        </article>
        <aside id="sidebar">
            <p>
                <em>"The best school in the world."</em>
                <br />
                <strong>- Albert Einstein</strong>
            </p>
        </aside>

    </div>
</section>

MVC-fab/MVC_Version/MVC_Version/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC-fab/MVC_Version/MVC_Version/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<section id="classes">

    <div class="container-1">
        <h4><u>Open Classes</u></h4>
        <table class="table">
            <thead>
            <tr></tr>
            </thead>
            <tbody>
            <tr>
                <td><strong>School</strong></td>
                <td><strong>Classes</strong></td>
                <td><strong>Open Slots</strong></td>
            </tr>
            <tr>
                <td>Data</td>
                <td>Data</td>
                <td>Data</td>
            </tr>
            <tr>
                <td>Data</td>
                <td>Data</td>
                <td>Data</td>
            </tr>
            <tr>
                <td>Data</td>
                <td>Data</td>
                <td>Data</td>
            </tr>
            <tr>
                <td>Data</td>
                <td>Data</td>
                <td>Data</td>
            </tr>
            <tr>
                <td>Data</td>
                <td>Data</td>
                <td>Data</td>
            </tr>

            </tbody>
        </table>
    </div>
    <div class="imgrot">

        <div id="jquery-slideshow-container">

            <ul id="jquery-slideshow">
                <li style="background-image: url(images/Fab_logo.png);">
                    <a href="https://www.example.com/some-page">
                        <span>Caption for slide #1 goes here.</span>
                    </a>
                </li>
                <li style="background-image: url(images/FU_image.png);">
                    <a href="https://www.example.com/another-page">
                        <span>Caption for slide #2 goes here.</span>
                    </a>
                </li>
                <li style="background-image: url(images/picture.png);">
                    <a href="https://www.example.com/lorem-ipsum-page">
                        <span>Caption for slide #3 goes here.</span>
                    </a>
                </li>
                <li style="background-image: url(images/school.jpg);">
                    <a href="https://www.example.com/lorem-ipsum-page">
                        <span>Caption for slide #4 goes here.</span>
                    </a>
                </li>
            </ul>

        </div>
        <div id="radioButtons">
            <div class="box-1"><input type="radio" name="place" value="0"></div>
            <div class="box-1"><input type="radio" name="place" value="1"></div>
            <div class="box-1"><input type="radio" name="place" value="2"></div>
            <div class="box-1"><input type="radio" name="place" value="3"></div>
        </div>
    </div>
    <div class="container-1">
        <h4><u>Register For</u></h4>
        <div class="container-2">

            <div class="box-1">
                <button type="button" class="btn-prft">Clubs</button>
            </div>
            <div class="box-1">
                <button type="button" class="btn-prft">Pay My Bill</button>
            </div>
            <div class="box-1">
                <button type="button" class="btn-prft">Campuses</button>
            </div>
            <div class="box-1">
                <button type="button" class="btn-prft">Contact Us</button>
            </div>

        </div>
    </div>
</section>

<div id="golden"></div>

<div class="d-flex justify-content-around flex-wrap container-3">
    <div class="box-2 college" id="img1">
        <h3 id="big">@Html.ActionLink("College of Computing and Digital Media", "Colofcd", "College")</h3>
    </div>
    <div class="box-2 college" id="img2">
        <h3>@Html.ActionLink("College of Education", "Colofed", "College")</h3>
    </div>
    <div class="box-2 college" id="img3">
        <h3>@Html.ActionLink("College of Law", "Coloflaw", "College")</h3>
    </div>
    <div class="box-2 college" id="img4">
        <h3>@Html.ActionLink("School of Music", "Schofmus", "College")</h3>
    </div>
</div>



@section scripts {
    @Scripts.Render("~/bundles/custom")
}